FROM node:16

# 가져올 이미지를 정의
FROM node:14

# 작업 경로 설정하기
WORKDIR /frontend_app

# 작업경로에 package.json 파일을 복사
COPY frontend/package.json .

# 명령어 실행 (의존성 설치)
RUN yarn install

# 설치된 모든 파일을 도커 컨테이너의 작업디렉토리에 복사
COPY . .

# 3000번 포트 노출
EXPOSE 3000

# npm start 스크립트 실행
CMD ["yarn", "start"]
