spring:
  profiles:
    active: local
    include:
      - core
      - domain
      - redis
      - rabbitmq
  mail:
    host: smtp.gmail.com
    port: 465
    username: ENC(FcYXf5BHgHzpQPBxG7jZLDfhu/OuIhLREvov1mbcIQc=)
    password: ENC(mcaGdPel0h2TQ7UAHGILs5RLeMp4WnmIqpMlqFaJTYs=)
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          timeout: 50000
          starttls:
            enable: true


riot:
  host: https://kr.api.riotgames.com
  apiKey: ENC(coxOvJA0JxD+bhtxqH/hOTF6iRSASTXsmLnhG3Fbro54skdk52iTahnedWs7xOzAckSf6hrr/vc=)
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: trace

