--- # CORS 공통 설정

# Access-Control-Request-Methods
# 리소스 접근을 허용하는 HTTP 메서드를 지정해주는 헤더
#
# Access-Control-Max-Age
# 클라이언트에서 Preflight 의 요청 결과를 캐시할 기간을 지정
# 첫 요청 이후 60초 동안은 OPTIONS 메소드를 사용하는 예비 요청을 보내지 않는다.
#
# Access-Control-Allow-Credentials
# 클라이언트 요청이 쿠키를 통해서 자격 증명을 해야 하는 경우에 true.
# 자바스크립트 요청에서 credentials가 include일 때 요청에 대한 응답을 할 수 있는지를 나타낸다.
#
# Access-Control-Allow-Origin
# 헤더에 작성된 출처만 브라우저가 리소스를 접근할 수 있도록 허용함.
# * 이면 모든 곳에 공개되어 있음을 의마한다.
access:
  control:
    methods: GET, POST, PUT, DELETE
    max-age: 60
    allow-credentials: true

--- # 개발 환경 설정
spring:
  config:
    activate:
      on-profile: local

access:
  control:
    allow-origin: http://localhost:3000

--- # production 설정
spring:
  config:
    activate:
      on-profile: production

access:
  control:
    allow-origin: ENC(kuVMfjlYFmuA0SO/cq4LvC2z3FQqOQe3)
