--- # 공통 설정
access:
  control:
    methods: GET, POST, PUT, PATCH, DELETE, OPTIONS # 설정된 종류의 메서드만 접근 허용
    max-age: 60 # 클라이언트는 설정된 시간만큼 Preflight 요청 결과를 캐시
    allow-credentials: true # 클라이언트에서 전송한 쿠키를 받아들임

--- # 개발 환경 설정
spring:
  config:
    activate:
      on-profile: local, test

access:
  control:
    allow-origin: http://localhost:3000 # 해당 출처만 서버에 접근 허용

my-server:
  backend:
    schme: http
    host: localhost
    port: 8080
  frontend:
    schme: http
    host: localhost
    port: 3000

--- # production 설정
spring:
  config:
    activate:
      on-profile: production

access:
  control:
    allow-origin: ENC(C7WHutmC+cxHA2wnqhEi5cxLeyhUiDTVnWymrJCZ1MzINHk5HwC54A==)

my-server:
  backend:
    schme: ENC(QFEQfw20COAuKLm+UR7zIQ==)
    host: ENC(rk+ixhn+BArGPVi8RoB/XZ4A1jvXFhgJ)
    port: ENC(Iiksuw9BQtXzeuCZU/wv9A==)
  frontend:
    schme: ENC(0tvH1BwOgbQZr8C8qes68Q==)
    host: ENC(pvw0z8Q4Fz4HVdqqU/C4MBYK10Rs0SHp)
    port: ENC(hqyZWH2NcJdz3sNJHnh0fA==)
