--- # local 설정

spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      port: 6379
      host: localhost

--- # production 설정

spring:
  config:
    activate:
      on-profile: production
  data:
    redis:
      port: 6379
      host: ENC(KnoFviKZlFsHLUq3AG7y4akFR9kPtt8z)
