--- #local and test

spring:
  config:
    activate:
      on-profile: local, test

  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest


--- # production

spring:
  config:
    activate:
      on-profile: production

  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest

