--- #local and test

spring:
  config:
    activate:
      on-profile: local, test

  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest


--- # production

spring:
  config:
    activate:
      on-profile: production

  rabbitmq:
    host: ENC(tZKUFfG/TeFuAbOqAcTCU3DVV8dAHYu6)
    port: 5672
    stream:
      username: ENC(459b7vftKFSOITZBCr+TRMYIQh8u0pv8)
      password: ENC(x9Hb0DDUAlX0snBI1TDVFw==)

