--- #local and test

spring:
  config:
    activate:
      on-profile: local, test

  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest


--- # production

spring:
  config:
    activate:
      on-profile: production

  rabbitmq:
    host: ENC(GNMsZxO77IbGbc/7xt3UQwFK04cGdykY)
    port: 5672
    stream:
      username: ENC(ymyw+tMsrjh8pkQfee+SFw==)
      password: ENC(v0gXOiqZ9j9Q5sp0GQtBVg==)

