spring:
  sql:
    init:
      mode: embedded
  jpa:
    hibernate:
      ddl-auto: update


--- # local 설정

spring:
  config:
    activate:
      on-profile: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/lol_judge
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

--- # production 설정

spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: ENC(vpdRbvKy8fKoFAcQZq9tC2Pc1KZkO2/9tj3ZcBrjddUE5wYgCrYkr0RHsIhQmy+NMMWE1pMnCba1ndXdsffHAOCmp3MoveGHhURlMRMs8Em2vY2C/UnjCsB6aGni/yZl8830xKyi2XgGFlkaQg54Aw==)
    username: ENC(v7Tk2YZmIzDiqHIuLllmKpEzbu9CNKd0)
    password: ENC(oARmjbL3j1cnW2kNHwbpNB7Ye2W1JRuU)
    driver-class-name: com.mysql.cj.jdbc.Driver
