spring:
  profiles:
    active: local
    include:
      - core
      - election
      - rabbitmq

--- # local

spring:
  config:
    activate:
      on-profile: local

api-url:
  host: localhost
  port: 8080

--- # production

spring:
  config:
    activate:
      on-profile: production

api-url:
  host: 118.67.134.233
  port: 8080

