spring:
  profiles:
    active: local
    include:
      - core
      - domain
      - rabbitmq
server:
  port: 8082

--- # local

spring:
  config:
    activate:
      on-profile: local

--- # production

spring:
  config:
    activate:
      on-profile: production

